class DuckType:
    def __str__(self): return self.__class__.__name__

class Integer(DuckType): ...
class BigInt(DuckType): ...
class Float(DuckType): ...
class Double(DuckType): ...
class Boolean(DuckType): ...
class Date(DuckType): ...
class Timestamp(DuckType): ...

class Varchar(DuckType):
    def __init__(self, length: int | None = None):
        self.length = length
    def __str__(self):
        return f"Varchar({self.length})" if self.length else "Varchar"
