[project]
name = "ducktyped"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.0",
    "ipykernel>=6.29.5",
    "polars>=1.30.0",
    "pyarrow>=20.0.0",
]
